---
version: '2'
services:
  els:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    restart: always
    container_name: els
    hostname: els
    networks:
    - web
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx2048m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ~/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./docker-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - "5601:5601"
    environment:
       ELASTICSEARCH_URL: http://els:9200
    depends_on:
    - els
    networks:
    - web
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    ports:
      - "8000:8000/tcp"
    depends_on:
      - els
    restart: unless-stopped
    container_name: logstash
    hostname: logstash
    networks:
      - web
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.3.0
    ports:
      - "14267:14267"
      - "14268:14268"
      - "9411:9411"
    depends_on:
    - els
    container_name: jaeger-collector
    hostname: jaeger-collector
    restart: unless-stopped
    networks:
    - web
    command: ["/go/bin/collector-linux", "--span-storage.type=elasticsearch", "--es.server-urls=http://els:9200"]
  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.3.0
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
    depends_on:
    - els
    - jaeger-collector
    restart: unless-stopped
    container_name: jaeger-agent
    hostname: jaeger-agent
    networks:
    - web
    command: ["/go/bin/agent-linux", "--collector.host-port=jaeger-collector:14267"]
  jaeger-query:
    image: jaegertracing/jaeger-query:1.3.0
    ports:
      - 16686:16686
    depends_on:
      - els
      - jaeger-collector
    restart: unless-stopped
    container_name: jaeger-query
    hostname: jaeger-query
    networks:
    - web
    command: ["/go/bin/query-linux", "--span-storage.type=elasticsearch", "--es.server-urls=http://els:9200", "--es.sniffer=false", "--query.static-files=/go/jaeger-ui/", "--log-level=debug"]
networks:
  web:
    driver: bridge
    